# COL_NAMES
COL_PROP = "prop"
COL_INSTANCE = "instance"
COL_MENTION = "mention"
COL_POSITIVE = "positive"
COL_DIRECT = "direct"
COL_CANDIDATES_IN_ABSTRACT = "cand_abs"
COL_CANDIDATES_IN_SENTENCE = "cand_sen"
COL_RELATIVE_CANDIDATE_IN_ABSTRACT = "rel_cand_abs"
COL_RELATIVE_CANDIDATE_IN_SENTENCE = "rel_cand_sen"
COL_ENTITIES_IN_SENTENCE = "ent_sen"
COL_RELATIVE_ENTITY_IN_ABSTRACT = "rel_ent_a"
COL_RELATIVE_ENTITY_IN_SENTENCE = "rel_ent_sen"
COL_RELATIVE_SENTENCE_IN_ABSTRACT = "rel_sen_abs"
COL_BACK_LINK = "back_link"

# SORTED_COL_GROUPS


NAME_COLS = [COL_PROP,
             COL_INSTANCE,
             COL_MENTION,
             COL_POSITIVE,
             COL_DIRECT,
             COL_CANDIDATES_IN_ABSTRACT,
             COL_CANDIDATES_IN_SENTENCE,
             COL_RELATIVE_CANDIDATE_IN_ABSTRACT,
             COL_RELATIVE_CANDIDATE_IN_SENTENCE,
             COL_ENTITIES_IN_SENTENCE,
             COL_RELATIVE_ENTITY_IN_ABSTRACT,
             COL_RELATIVE_ENTITY_IN_SENTENCE,
             COL_RELATIVE_SENTENCE_IN_ABSTRACT,
             COL_BACK_LINK
             ]

FEATURE_COLS = [COL_DIRECT,
                COL_CANDIDATES_IN_ABSTRACT,
                COL_CANDIDATES_IN_SENTENCE,
                COL_RELATIVE_CANDIDATE_IN_ABSTRACT,
                COL_RELATIVE_CANDIDATE_IN_SENTENCE,
                COL_ENTITIES_IN_SENTENCE,
                COL_RELATIVE_ENTITY_IN_ABSTRACT,
                COL_RELATIVE_ENTITY_IN_SENTENCE,
                COL_RELATIVE_SENTENCE_IN_ABSTRACT,
                COL_BACK_LINK
                ]
