from shexer.shaper import Shaper
from shexer.consts import NT, SHEXC
from wikipedia_shexer.core.fred_shape_extractor import FredShapeExtractor

def run(in_file_pattern, out_file_pattern, class_list):

    # with open(class_list_file, "r") as in_stream:
    #     for a_line in in_stream:
    #         print(a_line.strip())

    for a_class in class_list:
        print("Starting {}...".format(a_class))
        shaper = Shaper(all_classes_mode=True,
                        graph_file_input=in_file_pattern.format(a_class),
                        input_format=NT,
                        inverse_paths=True,
                        namespaces_dict=FredShapeExtractor.default_namespaces())
        shaper.shex_graph(acceptance_threshold=0,
                          output_format=SHEXC,
                          output_file=out_file_pattern.format(a_class))
        print ("{} done!".format(a_class))

if __name__ == "__main__":

    class_list = [
	"AcademicJournal",
	"Activity",
	"Actor",
	"AdministrativeRegion",
	"Aircraft",
	"Airport",
	"Album",
	"AmericanFootballPlayer",
	"Animal",
	"Arachnid",
	"Artist",
	"Artwork",
	"Athlete",
	"AustralianRulesFootballPlayer",
	"Automobile",
	"AutomobileEngine",
	"Award",
	"Band",
	"BaseballPlayer",
	"BasketballPlayer",
	"BasketballTeam",
	"Book",
	"Bridge",
	"BroadcastNetwork",
	"Building",
	"ChemicalCompound",
	"ChristianBishop",
	"City",
	"CollegeCoach",
	"ComicsCharacter",
	"ComicsCreator",
	"Company",
	"Country",
	"Cricketer",
	"Crustacean",
	"Currency",
	"Cyclist",
	"Device",
	"Diocese",
	"Disease",
	"Drug",
	"Enzyme",
	"EthnicGroup",
	"Eukaryote",
	"Event",
	"FictionalCharacter",
	"Film",
	"Fish",
	"Food",
	"FootballLeagueSeason",
	"Fungus",
	"GovernmentAgency",
	"Governor",
	"GridironFootballPlayer",
	"Gymnast",
	"HistoricBuilding",
	"HistoricPlace",
	"HockeyTeam",
	"IceHockeyPlayer",
	"InformationAppliance",
	"Insect",
	"Island",
	"Lake",
	"Language",
	"Legislature",
	"Magazine",
	"Mammal",
	"MemberOfParliament",
	"MilitaryConflict",
	"MilitaryPerson",
	"MilitaryStructure",
	"MilitaryUnit",
	"Mollusca",
	"MotorsportSeason",
	"Mountain",
	"Museum",
	"MusicalArtist",
	"MusicGenre",
	"NCAATeamSeason",
	"Newspaper",
	"Noble",
	"OlympicEvent",
	"Organisation",
	"Person",
	"Place",
	"Plant",
	"PoliticalParty",
	"Politician",
	"PowerStation",
	"President",
	"ProtectedArea",
	"PublicTransitSystem",
	"Publisher",
	"RadioStation",
	"RailwayLine",
	"RecordLabel",
	"ReligiousBuilding",
	"River",
	"Road",
	"Royalty",
	"RugbyClub",
	"RugbyPlayer",
	"Saint",
	"Sales",
	"School",
	"Scientist",
	"Settlement",
	"Ship",
	"SoccerClub",
	"SoccerClubSeason",
	"SoccerLeague",
	"SoccerManager",
	"SoccerPlayer",
	"SoccerTournament",
	"Software",
	"Song",
	"Species",
	"Sport",
	"SportsSeason",
	"SportsTeam",
	"SportsTeamMember",
	"Station",
	"Swimmer",
	"TelevisionEpisode",
	"TelevisionSeason",
	"TelevisionShow",
	"TelevisionStation",
	"TennisPlayer",
	"TimePeriod",
	"Town",
	"University",
	"Venue",
	"VideoGame",
	"Village",
	"VolleyballPlayer",
	"Weapon",
	"Website",
	"Wrestler",
	"Writer"
]
    run(in_file_pattern=r"F:\datasets\fred\triples_extra_types\{}.nt",
        out_file_pattern=r"F:\datasets\fred\shapes_extra_inverse\{}_extra_inverse.shex",
        class_list=class_list
        # class_list_file=r"F:\datasets\fred\outls.txt"
        )
    print("Done!")